### ISSUE TITLE
Autogroups seems to overwrite existing groups on every login

### ISSUE THREAD

**Issue by sjthiessen** [stjosh/auto_groups#70]
Hi,

currently, whenever an User logs in again, it gets removed from all manually assigned groups.
This occurred first when I activated the login hook, which was necessary as I'm using OIDC.

Now, I'm unable to revert this, even when disabling the AutoGroups App. Then I readded the app, unchecked all checkboxes and deleted all configured groups, still no change in behaviour. Inbetween I also tried the EveryoneGroup App in search for a solution.

Could someone help me to further investigate this?

**Comment by stjosh** [comment]
Thanks für reaching out!

I am surprised about the behavior you are reporting, as the auto_groups app only ever modifies group assignments related tho the groups referenced in its configuration. And the fact that you can‘t undo thus despite disabling the app makes me suspicious about the actual root cause of the behavior you see.

Unfortunately, I can only provide very limited support for SSO setups, as I don‘t have the capacity to test these constellations. But if someone from the community finds a way to fix this, I am very happy to accept pull requests.

**Comment by sjthiessen** [comment]
Hi, thanks for your reply!
I think i got a bit confused as Nextcloud doesn't cleanup all the remainings of an app once you remove it.
My issue was caused by a configurationin the sociallogin app.
So I'm sorry for bothering you with this..

**Comment by stjosh** [comment]
Glad to hear that the issue was resolved! 👍🏻
